/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'usb.debug+HP' 
 * Target:  'debug+HP' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* AlifSemiconductor::RTOS&AzureRTOS:Kernel:Core@6.2.1 */
// enabling global pre include
        #define TX_SINGLE_MODE_SECURE


#endif /* PRE_INCLUDE_GLOBAL_H */
